# Configuration Netlify pour TirageExpress
[build]
  # Dossier de publication (racine du projet)
  publish = "."
  
  # Dossier des fonctions Netlify
  functions = "netlify/functions"

# Configuration des fonctions
[functions]
  # Bundler pour les fonctions
  node_bundler = "esbuild"

# Redirections
[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
